### PR TITLE
fix security bugs

### PR DESCRIPTION
**Pull request by OskarLebuda**
Fix for #22.
Everything after update seems to work fine.

Result:
audit

### CODE REVIEW

**Comment by OskarLebuda** [comment]
@atomiomi  can u approve this PR? :)

**Comment by OskarLebuda** [comment]
@atomiomi ?

**Comment by atomiomi** [comment]
@OskarLebuda Merged, I will publish it during this week

**Comment by OskarLebuda** [comment]
@atomiomi  how about this release ? :)

**Comment by OskarLebuda** [comment]
@atomiomi  can you release this?

**Comment by OskarLebuda** [comment]
@atomiomi, can you release this package? We've been waiting for it for a long time...

**Pull request merged**
